task:
  name: alpineOpenssl
  only_if: $CIRRUS_BRANCH == 'native'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static rust cargo
    
  build_script:
    - whoami
    - cd openssl
    - ls -lah
    - rustc --version
    - cargo build --release --verbose

task:
  name: alpineNativeTLS
  only_if: $CIRRUS_BRANCH == 'native'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static rust cargo
    
  build_script:
    - whoami
    - cd native-tls
    - ls -lah
    - rustc --version
    - cargo build --release --verbose
    
task:
  name: alpineRustls
  only_if: $CIRRUS_BRANCH == 'native'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static rust cargo
    
  build_script:
    - whoami
    - cd rustls
    - ls -lah
    - rustc --version
    - cargo build --release --verbose