task:
  name: alpineOpenssl
  only_if: $CIRRUS_BRANCH == 'main'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    
  build_script:
    - whoami
    - cd openssl
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo build --release --verbose

task:
  name: alpineNativeTLS
  only_if: $CIRRUS_BRANCH == 'main'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    
  build_script:
    - whoami
    - cd native-tls
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo build --release --verbose
    
task:
  name: alpineRustls
  only_if: $CIRRUS_BRANCH == 'main'
    
  arm_container:
    image: alpine:latest
    cpu: 4
    
  prepare_script:
    - apk -U upgrade
    - apk add curl make pkgconf bash build-base openssl openssl-dev openssl-libs-static
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - . $HOME/.cargo/env
    
  build_script:
    - whoami
    - cd rustls
    - . $HOME/.cargo/env
    - ls -lah
    - rustc --version
    - cargo build --release --verbose