[package]
name = "native-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-resolver = {version = "*", features = ["dns-over-native-tls"]}  # Apache 2.0 / MIT